routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





/*
 * Unprotected Routes
 */

Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/latestuploads', 'FileController@latest')->name('files.latest');
Route::get('/popularuploads', 'FileController@popular')->name('files.popular');

Route::get('/test', 'HomeController@testmessages')->name('home.testmessages');
Route::get('/download/{id}/{_uid}', 'FileController@single')->name('files.single');
Route::get('/theme/{theme}', 'ThemeController@switchTheme')->name('theme.switch');


Route::post('/files/upload', 'UploadController@store')->name('files.store');
Route::post('/files/download/{id}/{uid}', 'DownloadController@single')->name('download.single');

Route::get('/files/staticupload', 'FileController@staticuploadget')->name('files.staticuploadget');
Route::post('/files/staticupload', 'FileController@staticuploadpost')->name('files.staticuploadpost');
Route::post('files/settingsmeta', 'FileController@getMetaFileSettings')->name('files.checksettingssize');

/*
 * Protected Routes for front end / auth only
 */
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Auth::routes();


/*
 * Start wrapping the Admin Middleware protected Routes
 */

Route::namespace('Admin')->prefix('rpanel')->name('admin.')->middleware('isAdmin')->group(function () {

    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('users','UserController');
    Route::resource('files','FileController');
    Route::resource('settings','SettingsController');
    Route::resource('comments','CommentController');
    Route::resource('ads','AdController');
    Route::resource('reports','ReportController');
    Route::resource('filesettings','FileSettingsController');
    Route::resource('staticpages','StaticPageController');
    Route::resource('siteinfo','SiteInfoController');
    Route::resource('cleaner','CleanerController');
    Route::resource('ads','AdController');

    Route::post('settings/dircleaner/remove', 'CleanerController@remove')->name('cleaner.remove');

});

resources/views/admin/_static/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.0.0-rc.1
    </div>
    <strong>Copyright &copy;   UI based on AdminLTE</strong>  All rights
    reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{asset('plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('js/demo.js')}}"></script>
</body>
</html>

resources/views/admin/_static/header.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('css/adminlte.min.css')}}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

resources/views/admin/_static/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{route('home.index')}}" class="nav-link" target="_blank">Go To Front</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Logout Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-user-alt mr-2"></i>
                <i class="fa fa-arrow-alt-circle-down"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-md-right dropdown-menu-right">
                <a href="{{route('logout')}}" class="dropdown-item">
                    <i class="fas fa-sign-out-alt mr-2"></i>
                    Logout
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

resources/views/admin/_static/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->


    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">

            <div class="info">

                <a href="#" class="d-block">Welcome</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->

                <li class="nav-item">
                    <a href="{{route('admin.dashboard.index')}}" class="nav-link active">
                        <i class="nav-icon fas fa-home"></i>
                        <p>
                            Welcome
                        </p>
                    </a>
                </li>
                <li class="nav-item has-treeview">
                    <a href="" class="nav-link">
                        <i class="nav-icon fas fa-cogs"></i>
                        <p>
                            Site Settings
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('admin.settings.index')}}" class="nav-link">
                                <i class="fas fa-cog nav-icon"></i>
                                <p>General Settings</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.siteinfo.index')}}" class="nav-link">
                                <i class="fas fa-info nav-icon"></i>
                                <p>Current Site Information</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.cleaner.index')}}" class="nav-link">
                                <i class="fa fa-trash nav-icon"></i>
                                <p>Dir Cleaner</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/phpinfo" class="nav-link">
                                <i class="fa fa-info nav-icon"></i>
                                <p>Full PHP Info</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            Files
                            <i class="fas fa-angle-left right"></i>
                            <span class="badge badge-info right">{{$filescount}}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">

                        <li class="nav-item">
                            <a href="{{route('admin.files.index')}}" class="nav-link">
                                <i class="fas fa-file-archive nav-icon"></i>
                                <p>All Files</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('admin.filesettings.index')}}" class="nav-link">
                                <i class="fas fa-cog nav-icon"></i>
                                <p>File Settings</p>
                            </a>
                        </li>




                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-user-secret"></i>
                        <p>
                          Users
                            <i class="fas fa-angle-left right"></i>
                            <span class="badge badge-info right">{{$userscount}}</span>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('admin.users.index')}}" class="nav-link">
                                <i class="fas fa-user-alt nav-icon"></i>
                                <p>All Users</p>
                            </a>
                        </li>


                    </ul>
                </li>

                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-ad"></i>
                        <p>
                           Ads Management
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('admin.ads.index')}}" class="nav-link">
                                <i class="fas fa-cog nav-icon"></i>
                                <p>Ads</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-pager"></i>
                        <p>
                           Pages
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{route('admin.staticpages.index')}}" class="nav-link">
                                <i class="fas fa-pager nav-icon"></i>
                                <p>Pages</p>
                            </a>
                        </li>

                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon far fa-circle text-info"></i>
                        <p>Documentation</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>