routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





/*
 * Unprotected Routes
 */

Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/latestuploads', 'FileController@latest')->name('files.latest');
Route::get('/popularuploads', 'FileController@popular')->name('files.popular');

Route::get('/test', 'HomeController@testmessages')->name('home.testmessages');
Route::get('/download/{id}/{_uid}', 'FileController@single')->name('files.single');
Route::get('/theme/{theme}', 'ThemeController@switchTheme')->name('theme.switch');


Route::post('/files/upload', 'UploadController@store')->name('files.store');
Route::post('/files/download/{id}/{uid}', 'DownloadController@single')->name('download.single');

Route::get('/files/staticupload', 'FileController@staticuploadget')->name('files.staticuploadget');
Route::post('/files/staticupload', 'FileController@staticuploadpost')->name('files.staticuploadpost');
Route::post('files/settingsmeta', 'FileController@getMetaFileSettings')->name('files.checksettingssize');

/*
 * Protected Routes for front end / auth only
 */
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Auth::routes();


/*
 * Start wrapping the Admin Middleware protected Routes
 */

Route::namespace('Admin')->prefix('rpanel')->name('admin.')->middleware('isAdmin')->group(function () {

    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('users','UserController');
    Route::resource('files','FileController');
    Route::resource('settings','SettingsController');
    Route::resource('comments','CommentController');
    Route::resource('ads','AdController');
    Route::resource('reports','ReportController');
    Route::resource('filesettings','FileSettingsController');
    Route::resource('staticpages','StaticPageController');
    Route::resource('siteinfo','SiteInfoController');
    Route::resource('cleaner','CleanerController');
    Route::resource('ads','AdController');

    Route::post('settings/dircleaner/remove', 'CleanerController@remove')->name('cleaner.remove');

});

app/File.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\URL;

class File extends Model
{
    protected $guarded = [];


    public function user() {
        return $this->belongsTo('App\User');
    }
    public function fileslug() {
        return URL::to('download/'. $this->id . '/' . $this->uid);
    }

    public function imgsrc() {
        return $this->fullpath;
    }

    public function is_image() {
        $imageExtensions = ['jpg', 'jpeg', 'gif', 'png', 'bmp', 'svg',
            'svgz', 'cgm', 'djv', 'djvu', 'ico', 'ief','jpe', 'pbm', 'pgm', 'pnm',
            'ppm', 'ras', 'rgb', 'tif', 'tiff', 'wbmp', 'xbm', 'xpm', 'xwd'];

        $explodeImage = explode('.', 'image-name-here');
        $extension = $this->extension;

        if(in_array($extension, $imageExtensions))
        {
            return true;
        }
            else
        {
            return false;
        }
    }



}

app/Http/Controllers/Admin/FileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\FileRequest;

class FileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $files = File::with('user')->orderBy('created_at','DESC')->paginate(10);

        return view('admin.files.index',compact('files'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FileRequest $request)
    {


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $file = File::find($id);

        if($file) {
            return view('admin.files.edit',compact('file'));

        }
        else {
            return back()->with('error','File Not Exist');
        }

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $file = File::find($id);
        $data = $request->all();

        if($file){
            $file->update($data);

            return redirect()->route('admin.files.index')->with('success','File is Edited');

        }
        else {
            return redirect()->back()->with('error','File with the ID not found');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $file = File::find($id);
        $path =   public_path($file->relative_path);
        $relpath = $file->fullpath;
        $filemessage = 'And file not removed from DISK';


        if(@unlink($path)) {
                $filemessage = 'And file removed from disk';

            }



        $file->delete();

        return redirect()->route('admin.files.index')->with('success','File removed from DB ' . $filemessage);

    }
}

app/Http/Controllers/FileController.php
<?php

namespace App\Http\Controllers;

use App\File;
use Illuminate\Http\Request;
use App\Settings;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
class FileController extends Controller
{


  public function getMetaFileSettings() {
   $settings = Settings::find(1);
   $filesettings = [];
   $filesettings->maxsize = $settings->file_maxsize_kb;
   $filesettings->minsize = $settings->file_minsize_kb;


    return response()->json($filesettings,200);


  }

    public function popular() {
        $files = File::
            where('is_active',1)
            ->orderBy('views','DESC')
            ->paginate(5);

        if($files) {
            return view('files.popularfiles',compact('files'));
        }
    }

    public function latest()
    {
        $files = File::with('user')
            ->where('is_active',1)
            ->orderBy('created_at','DESC')
            ->paginate(5);

        if($files) {
            return view('files.recentfiles',compact('files'));
        }

    }



    public function single($id, $fileslug)
    {
        $file = File::find($id);

        if($file) {
            $file->views ++;
            $file->save();

            return view('files.single',compact('file'));


        }
        else {
            redirect()->back()->with('error','File Not Found');

        }

    }


}

resources/views/admin/files/edit.blade.php
@extends('admin.layouts.app')

@section('title')Edit File {{$file->saved_name}}@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <h5 class="mb-2">Edit File: {{$file->saved_name}}</h5>

            <form action="{{route('admin.files.update',$file->id)}}" method="POST" enctype="multipart/form-data">
                @csrf('put')
                <div class="row">
                    <div class="col-lg-8">
                        @method('put')

                        <div class="card card-info">
                            <div class="card-header">
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                        <i class="fas fa-minus"></i></button>
                                    <button type="button" class="btn btn-tool"
                                            data-card-widget="remove"><i class="fas fa-times"></i></button>
                                </div>
                                <h3 class="card-title">General Information</h3>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <small>Path of the file.</small>
                                        <div class="input-group mb-3">
                                            <input type="text" class="form-control" value="{{$file->fullpath}}"
                                                   name="fullpath" disabled>
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">.{{$file->extension}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-8">
                                        <p>Original Name</p>
                                        <div class="input-group mb-3">


                                            <input type="text" class="form-control" value="{{$file->original_name}}"
                                                   name="original_name" disabled>
                                            <div class="input-group-prepend">

                                                <span class="input-group-text">{{$file->extension}}</span>
                                            </div>
                                        </div>
                                        <p>Saved Name</p>
                                        <div class="input-group mb-3">


                                            <input type="text" class="form-control" value="{{$file->saved_name}}"
                                                   name="saved_name">
                                            <div class="input-group-prepend">

                                                <span class="input-group-text">{{$file->extension}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <p>File Size</p>
                                        <div class="input-group mb-3">
                                            <input type="text" class="form-control" value="
                                                {{\App\Helpers\Helper::bytesToHuman($file->size)}}"
                                                   name="name" disabled>
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <p>File UID</p>
                                                <div class="input-group mb-3">

                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"><i class="fas
                                                        fa-pager"></i></span>
                                                    </div>
                                                    <input type="text" class="form-control" value="{{$file->uid}}"
                                                           name="uid"
                                                           disabled>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label>Is File Active?</label>
                                            <select class="form-control" name="is_active">
                                                <option value="1" {{$file->is_active ? 'selected' : ''}}>Yes</option>
                                                <option value="0" {{$file->is_active ? '' : 'selected'}}>No</option>

                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            <button type="submit" class="btn btn-block btn-info btn-lg">Edit File</button>
                        </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="card card-blue collapsed-card">
                            <div class="card-header ">
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                            class="fas fa-plus"></i></button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                                        <i class="fas fa-times"></i></button>
                                </div>
                                <h3 class="card-title">Views and Downloads</h3>
                            </div>
                            <div class="card-body">
                                <div class="input-group mb-3">

                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"><i class="fas
                                                        fa-eye"></i></span>
                                    </div>
                                    <input type="number" class="form-control" value="{{$file->views}}" name="views"
                                           >
                                </div>
                                <div class="input-group mb-3">

                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"><i class="fas
                                                        fa-download"></i></span>
                                    </div>
                                    <input type="number" class="form-control" value="{{$file->downloads }}"
                                           name="downloads"
                                           >
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </form>

        </div>
    </section>
@stop

resources/views/admin/files/index.blade.php
@extends('admin.layouts.app')

@section('title','All Files')

@section('content')
    <section class="content">
        <div class="container-fluid">
            <h5 class="mb-2">Files</h5>

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">All Files</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fas fa-times"></i></button>
                    </div>
                </div>
                <div class="card-body p-0">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th style="">
                                #ID
                            </th>
                            <th style="">
                                MimeType
                            </th>
                            <th style="">
                               Orig.Name
                            </th>
                            <th>Date</th>

                            <th style="">
                               Extension
                            </th>
                            <th>
                                is Active?
                            </th>
                            <th style="" class="">
                               Views
                            </th>
                            <th style="" class="">
                                Downloads
                            </th>

                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse ($files as $file)
                            <tr class="{{$file->is_active ? '' : 'text-danger'}}">
                                <td>
                                    {{$file->id}}
                                </td>
                                <td>
                                    {{$file->mimetype}}

                                </td>
                                <td>{{$file->saved_name}}</td>
                                <td>{{$file->created_at->diffForHumans()}}</td>

                                <td>
                                    .{{$file->extension}}
                                </td>

                                <td>
                                   @if($file->is_active)
                                       Yes
                                    @else
                                        No
                                    @endif

                                </td>
                                <td>
                                    {{$file->views}}
                                </td>
                                <td>
                                    {{$file->downloads}}
                                </td>

                                <td class="project-actions ">
                                    <a class="btn btn-info btn-sm"
                                       href="{{route('files.single',['id' => $file->id,'uid' => $file->uid])}}" target="_blank">
                                        <i class="fas fa-download"></i>
                                        View
                                    </a>

                                    <a class="btn btn-info btn-sm" href="{{route('admin.files.edit',$file->id)}}">
                                        <i class="fas fa-pencil-alt"></i>
                                        Edit
                                    </a>

                                    <a class="btn btn-danger btn-sm" href="#" data-toggle="modal"
                                       data-target="#modal-danger-{{$file->id}}">
                                        <i class="fas fa-trash"></i>
                                        Delete
                                    </a>

                                </td>
                            </tr>
                            <div class="modal fade" id="modal-danger-{{$file->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-danger ">
                                        <div class="modal-header text-center">
                                            <h4 class="modal-title">Delete File Permanently?</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>

                                        <div class="modal-footer justify-content-between text-center">
                                            <form action="{{route('admin.files.destroy',$file->id)}}" method="POST">
                                                @method('delete')
                                                @csrf
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        @empty
                            <hr>
                            <h3 class="ml-4">No Files found</h3>

                        @endforelse


                        </tbody>
                    </table>
                    {{ $files->links() }}
                </div>

            </div>

        </div>
    </section>
@stop