routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





/*
 * Unprotected Routes
 */

Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/latestuploads', 'FileController@latest')->name('files.latest');
Route::get('/popularuploads', 'FileController@popular')->name('files.popular');

Route::get('/test', 'HomeController@testmessages')->name('home.testmessages');
Route::get('/download/{id}/{_uid}', 'FileController@single')->name('files.single');
Route::get('/theme/{theme}', 'ThemeController@switchTheme')->name('theme.switch');


Route::post('/files/upload', 'UploadController@store')->name('files.store');
Route::post('/files/download/{id}/{uid}', 'DownloadController@single')->name('download.single');

Route::get('/files/staticupload', 'FileController@staticuploadget')->name('files.staticuploadget');
Route::post('/files/staticupload', 'FileController@staticuploadpost')->name('files.staticuploadpost');
Route::post('files/settingsmeta', 'FileController@getMetaFileSettings')->name('files.checksettingssize');

/*
 * Protected Routes for front end / auth only
 */
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Auth::routes();


/*
 * Start wrapping the Admin Middleware protected Routes
 */

Route::namespace('Admin')->prefix('rpanel')->name('admin.')->middleware('isAdmin')->group(function () {

    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('users','UserController');
    Route::resource('files','FileController');
    Route::resource('settings','SettingsController');
    Route::resource('comments','CommentController');
    Route::resource('ads','AdController');
    Route::resource('reports','ReportController');
    Route::resource('filesettings','FileSettingsController');
    Route::resource('staticpages','StaticPageController');
    Route::resource('siteinfo','SiteInfoController');
    Route::resource('cleaner','CleanerController');
    Route::resource('ads','AdController');

    Route::post('settings/dircleaner/remove', 'CleanerController@remove')->name('cleaner.remove');

});

resources/views/admin/welcome/index.blade.php
@extends('admin.layouts.app')

@section('title','Welcome To Admin Panel')
@section('content')
    <section class="content">
        <div class="container-fluid">
            <h5 class="mb-2">Recent Details</h5>
            <div class="row">


                <div class="col-md-12 col-sm-12 col-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-warning"><i class="far fa-copy"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text"><a href="{{route('admin.files.index')}}">View All
                                    Files</a></span>
                            <span class="info-box-number">{{$filescount}}</span>
                        </div>

                    </div>
                    <div class="card card-success">
                        <div class="card-header">
                            <h3 class="card-title">Recent Files</h3>

                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                                <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                            </div>
                            <!-- /.card-tools -->
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body" style="display: block;">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th style="width: 10px">#</th>
                                    <th>file name</th>
                                    <th>is active</th>
                                    <th>Date</th>
                                    <th style="width: 40px">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse ($latestfiles->sortByDesc('created_at') as $file)
                                    <tr>
                                        <td>{{$file->id}}</td>
                                        <td>{{str_limit($file->original_name),10,'...'}}</td>
                                        <td>
                                            {{$file->is_active ? 'Yes' : 'No'}}
                                        </td>
                                        <td>{{$file->created_at->diffForHumans()}}</td>
                                        <td>
                                            <a href="{{route('admin.files.edit',$file->id)}}" class="btn btn-info
                                            btn-sm">
                                                <i class="fa fa-pencil"></i>Edit
                                            </a>
                                        </td>
                                    </tr>
                                @empty
                                    No Files Found
                                @endforelse
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@stop