routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





/*
 * Unprotected Routes
 */

Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/latestuploads', 'FileController@latest')->name('files.latest');
Route::get('/popularuploads', 'FileController@popular')->name('files.popular');

Route::get('/test', 'HomeController@testmessages')->name('home.testmessages');
Route::get('/download/{id}/{_uid}', 'FileController@single')->name('files.single');
Route::get('/theme/{theme}', 'ThemeController@switchTheme')->name('theme.switch');


Route::post('/files/upload', 'UploadController@store')->name('files.store');
Route::post('/files/download/{id}/{uid}', 'DownloadController@single')->name('download.single');

Route::get('/files/staticupload', 'FileController@staticuploadget')->name('files.staticuploadget');
Route::post('/files/staticupload', 'FileController@staticuploadpost')->name('files.staticuploadpost');
Route::post('files/settingsmeta', 'FileController@getMetaFileSettings')->name('files.checksettingssize');

/*
 * Protected Routes for front end / auth only
 */
Route::get('/logout', 'Auth\LoginController@logout')->name('logout' );
Auth::routes();


/*
 * Start wrapping the Admin Middleware protected Routes
 */

Route::namespace('Admin')->prefix('rpanel')->name('admin.')->middleware('isAdmin')->group(function () {

    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('users','UserController');
    Route::resource('files','FileController');
    Route::resource('settings','SettingsController');
    Route::resource('comments','CommentController');
    Route::resource('ads','AdController');
    Route::resource('reports','ReportController');
    Route::resource('filesettings','FileSettingsController');
    Route::resource('staticpages','StaticPageController');
    Route::resource('siteinfo','SiteInfoController');
    Route::resource('cleaner','CleanerController');
    Route::resource('ads','AdController');

    Route::post('settings/dircleaner/remove', 'CleanerController@remove')->name('cleaner.remove');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];





}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('created_at','DESC')->paginate(15);

        return view('admin.users.index',compact('users'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        if($user) {
            return view('admin.users.edit',compact('user'));
        }

        else {
            return redirect()->route('admin.users.index')->with('error','User not found');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        if($user) {

            $user->name = $request['name'];
            $user->email = $request['email'];
            $user->about = $request['about'];
            $user->is_admin = $request['is_admin']; // role 1 is regular, 2 moderator, 3 admin




            $user->save();

            return redirect()->route('admin.users.index')->with('success','User Edited');

        }
        else {
            return redirect()->route('admin.users.index')->with('error','User Not Found');


        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if($user) {
            User::destroy($user);
            return back()->with('info','User is permanently Deleted');
        }
        else {
            return back()->with('warning','User not found');
        }
    }
}

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('title')Edit User {{$user->name}}@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <h5 class="mb-2">Edit User: {{$user->name}}</h5>

            <form action="{{route('admin.users.update',$user->id)}}" method="POST" enctype="multipart/form-data">
                @csrf('put')
                <div class="row">
                    <div class="col-lg-8">
                        @method('put')


                        <div class="card card-info">
                            <div class="card-header">
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                            class="fas fa-minus"></i></button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                                </div>
                                <h3 class="card-title">General Information</h3>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <p>Name</p>
                                        <div class="input-group mb-3">

                                            <div class="input-group-prepend">
                                                <span class="input-group-text">@</span>
                                            </div>
                                            <input type="text" class="form-control" value="{{$user->name}}"
                                                   name="name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <p>Email Adress</p>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                            </div>
                                            <input type="email" class="form-control" value="{{$user->email}}" name="email">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <p>UID</p>
                                                <div class="input-group mb-3">

                                                    <div class="input-group-prepend">
                                                        <span class="input-group-text"><i class="fa fa-user"></i></span>
                                                    </div>
                                                    <input type="text" class="form-control" value="{{$user->uid}}" name="uid"
                                                           disabled>
                                                </div>
                                            </div>

                                        </div>

                                        <div class="form-group">
                                            <label>Can User Upload Files?</label>
                                            <select class="form-control" name="is_upload_allowed">
                                                <option value="1">Yes</option>
                                                <option value="0">No</option>

                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-lg-12">

                                        <div class="form-group">
                                            <label>About</label>
                                            <textarea class="form-control" rows="3" name="about">{{$user->about}}</textarea>
                                        </div>
                                    </div>


                                </div>

                            </div>
                            <hr>

                        </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="card card-blue collapsed-card">
                            <div class="card-header ">
                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                            class="fas fa-plus"></i></button>
                                    <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i></button>
                                </div>
                                <h3 class="card-title">Other User Settings</h3>
                            </div>

                        </div>

                    </div>
                </div>
            </form>

        </div>
    </section>
@stop

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('title')All Users
@stop

@section('content')
    <section class="content">
        <div class="container-fluid">
            <h5 class="mb-2">Users</h5>

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">All Users</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fas fa-minus"></i></button>
                        <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fas fa-times"></i></button>
                    </div>
                </div>
                <div class="card-body p-0">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th style="">
                                #ID
                            </th>
                            <th style="">
                                Name
                            </th>
                            <th>
                                Registered
                            </th>
                            <th style="">
                                Email
                            </th>

                            <th style="" class="">
                                Role
                            </th>
                           <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse ($users as $user)
                            <tr>
                                <td>
                                    {{$user->id}}
                                </td>
                                <td>
                                    {{$user->name}}

                                </td>
                                <td>
                                    {{$user->created_at->diffForHumans()}}
                                </td>
                                <td>
                                    {{$user->email}}
                                </td>

                                <td>
                                    {{$user->is_admin ? 'Admin' : 'Regular User'}}
                                </td>
                                <td class="project-actions ">
                                    <a class="btn btn-info btn-sm" href="{{route('admin.users.edit',$user->id)}}">
                                        <i class="fas fa-pencil-alt"></i>
                                        Edit
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="#" data-toggle="modal" data-target="#modal-danger-{{$user->id}}">
                                        <i class="fas fa-trash"></i>
                                        Delete
                                    </a>
                                </td>
                            </tr>
                            <div class="modal fade" id="modal-danger-{{$user->id}}">
                                <div class="modal-dialog">
                                    <div class="modal-content bg-danger ">
                                        <div class="modal-header text-center">
                                            <h4 class="modal-title">Delete User Permanently?</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>

                                        <div class="modal-footer justify-content-between text-center">
                                            <form action="{{route('admin.users.destroy',$user->id)}}" method="POST">
                                                @method('delete')
                                                @csrf
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                            <button type="button" class="btn btn-outline-light" data-dismiss="modal">Cancel</button>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        @empty
                            <hr>
                            <h3 class="ml-4">No Users found</h3>

                        @endforelse


                        </tbody>
                    </table>
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </section>
@stop